
import React, { useState, useCallback } from 'react';
import { analyzeSeo } from './services/geminiService';
import { SeoAnalysisResult } from './types';
import Input from './components/Input';
import Button from './components/Button';
import Loader from './components/Loader';
import ResultCard from './components/ResultCard';

const App: React.FC = () => {
    const [url, setUrl] = useState<string>('');
    const [keyword, setKeyword] = useState<string>('');
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);
    const [results, setResults] = useState<SeoAnalysisResult | null>(null);

    const handleAnalyze = useCallback(async () => {
        if (!url || !keyword) {
            setError('Please provide both a URL and a keyword.');
            return;
        }
        
        // Basic URL validation
        try {
            new URL(url);
        } catch (_) {
            setError('Please enter a valid URL (e.g., https://example.com).');
            return;
        }

        setIsLoading(true);
        setError(null);
        setResults(null);

        try {
            const analysisResults = await analyzeSeo(url, keyword);
            setResults(analysisResults);
        } catch (e) {
            console.error(e);
            setError('An error occurred during analysis. Please check the console or try again.');
        } finally {
            setIsLoading(false);
        }
    }, [url, keyword]);

    return (
        <div className="min-h-screen bg-slate-900 text-slate-200 font-sans flex flex-col items-center p-4 sm:p-6 lg:p-8">
            <div className="w-full max-w-4xl mx-auto">
                <header className="text-center mb-10">
                    <h1 className="text-4xl sm:text-5xl font-bold text-white mb-2">Gemini SEO Analyzer</h1>
                    <p className="text-lg text-slate-400">
                        Get instant on-page SEO analysis powered by the Gemini API.
                    </p>
                </header>

                <main>
                    <div className="bg-slate-800/50 backdrop-blur-sm p-6 sm:p-8 rounded-2xl shadow-2xl border border-slate-700">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                            <Input
                                id="url"
                                label="Website URL"
                                placeholder="https://example.com"
                                value={url}
                                onChange={(e) => setUrl(e.target.value)}
                                disabled={isLoading}
                            />
                            <Input
                                id="keyword"
                                label="Target Keyword"
                                placeholder="e.g., sustainable coffee"
                                value={keyword}
                                onChange={(e) => setKeyword(e.target.value)}
                                disabled={isLoading}
                            />
                        </div>
                        <Button onClick={handleAnalyze} disabled={isLoading || !url || !keyword}>
                            {isLoading ? 'Analyzing...' : 'Analyze'}
                        </Button>
                        {error && <p className="text-red-400 mt-4 text-center">{error}</p>}
                    </div>

                    {isLoading && <Loader />}

                    {results && (
                        <div className="mt-12">
                            <h2 className="text-3xl font-bold text-center mb-8">Analysis Results</h2>
                            <p className="text-center text-slate-500 mb-8 -mt-6 text-sm">
                                Note: This analysis is generated by an AI model and may not reflect the live page with 100% accuracy.
                            </p>
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                <ResultCard title="Title Tag" data={results.title} />
                                <ResultCard title="Meta Description" data={results.metaDescription} />
                                <ResultCard title="H1 Tags" data={results.h1Tags} />
                                <ResultCard title="Image Alt Tags" data={results.images} />
                                <ResultCard title="Page Word Count" data={results.wordCount} />
                                <ResultCard title="Keyword Placement" data={results.keywordAnalysis} />
                            </div>
                        </div>
                    )}
                </main>

                <footer className="text-center mt-12 text-slate-500 text-sm">
                    <p>Built with React, Tailwind CSS, and the Google Gemini API.</p>
                </footer>
            </div>
        </div>
    );
};

export default App;
